openapi: 3.0.4

info:
  title: Storey
  version: 1.0.0
  description: >
    Save your money by buying the most budget-friendly products between multiple
    options, and plan your shopping beforehand.

paths:
  ### ======================== Products ======================== ###

  /products:
    get:
      summary: Get a list of products.
      tags:
        - Product
      parameters:
        - $ref: '#/components/parameters/pageParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/sortParam'
      responses:
        '200':
          description: Returns a list of products.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListWithPageResponse'
    post:
      summary: Create a new product.
      tags:
        - Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductInput'
      responses:
        '201':
          description: Returns the newly created product.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/ResponseStatus'
                  data:
                    $ref: '#/components/schemas/Product'

  /products/{id}:
    parameters:
      - $ref: '#/components/parameters/idParam'

    get:
      summary: Get a product details.
      tags:
        - Product
      responses:
        '200':
          description: Returns a product details based on given product ID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/ResponseStatus'
                  data:
                    $ref: '#/components/schemas/Product'
    patch:
      summary: Edit a product details.
      tags:
        - Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditProductInput'
      responses:
        '200':
          description: Returns the edited product.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/ResponseStatus'
                  data:
                    $ref: '#/components/schemas/Product'
    delete:
      summary: Delete a product.
      tags:
        - Product
      responses:
        '200':
          description: Returns the deleted product.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/ResponseStatus'
                  data:
                    $ref: '#/components/schemas/Product'

  /products/{id}/price:
    patch:
      summary: Change product price.
      tags:
        - Product
      parameters:
        - $ref: '#/components/parameters/idParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                price:
                  type: number
      responses:
        '200':
          description: Returns the product's new pricing information.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/ResponseStatus'
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                      price:
                        type: number
                      pricePerUnit:
                        type: number
                        format: float
                    example:
                      _id: 507f1f77bcf86cd799439011
                      price: 3000
                      netto: 80.00
                      unit: g
                      pricePerUnit: 37.50

  ### ======================== Images ======================== ###

  /image:
    post:
      summary: Upload new images to cloud storage.
      tags:
        - Image
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                images:
                  type: array
                  description: 'Array of image files. Supported formats: PNG, JPEG, WebP. Maximum 5 files per request.'
                  items:
                    type: string
                    format: binary
                  minItems: 1
                  maxItems: 5
            encoding:
              images:
                contentType: image/png, image/jpeg, image/webp
      responses:
        '200':
          description: Successful image upload. Returns an array of uploaded images public ID and URL.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/ResponseStatus'
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Image'

    delete:
      summary: Delete images from cloud storage.
      tags:
        - Image
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Image'
              description: An array of images that are about to be deleted.
      responses:
        '204':
          description: Successful image deletion.

  ### ======================== User ======================== ###

  /user/register:
    post:
      summary: Register a new user.
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegisterInput'
      responses:
        '200':
          description: Successful user registration. Returns basic user information and establish a login session.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/ResponseStatus'
                  data:
                    type: object
                    properties:
                      username:
                        type: string
                    example:
                      username: JohnDoe

  /user/login:
    post:
      summary: User login.
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginInput'
      responses:
        '200':
          description: Successful user login. Returns basic user information and establish a login session.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/ResponseStatus'
                  data:
                    type: object
                    properties:
                      username:
                        type: string
                    example:
                      username: JohnDoe

  /user/logout:
    get:
      summary: User logout.
      tags:
        - User
      responses:
        '204':
          description: Successful user logout.

  /user/categories:
    post:
      summary: Create a new category to user's category list.
      tags:
        - User
      requestBody:
        content:
          text/plain:
            example: ml

components:
  schemas:
    ### ======================== Product ======================== ###

    Product:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        description:
          type: string
        images:
          type: array
          items:
            $ref: '#/components/schemas/Image'
        categories:
          $ref: '#/components/schemas/Categories'
        price:
          type: number
        netto:
          type: number
          format: float
        unit:
          $ref: '#/components/schemas/Unit'
        pricePerUnit:
          type: number
          format: float
        store:
          $ref: '#/components/schemas/Store'
        pinned:
          type: boolean
          default: false
        author:
          $ref: '#/components/schemas/User'
        createdAt:
          type: string
          format: date-time
      example:
        _id: 507f1f77bcf86cd799439011
        name: Indomie Goreng
        description: The best instant fried noodle in Indonesia.
        images:
          - publicId: public_id
            url: https://photo.com/path-to-image.png
        categories:
          - food
        price: 3000
        netto: 80.00
        unit: g
        pricePerUnit: 37.50
        store:
          name: Indomaret Nglegok
          address: Jl. Raya Penataran, Nglegok 1, Nglegok, Kec. Nglegok, Kabupaten Blitar, Jawa Timur
        pinned: true,
        author:
          username: 'JohnDoe'
        createdAt: 2025-09-12T03:57:00.600Z
    ProductInputBase:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        images:
          type: array
          items:
            $ref: '#/components/schemas/Image'
        categories:
          $ref: '#/components/schemas/Categories'
        price:
          type: number
        netto:
          type: number
          format: float
        unit:
          $ref: '#/components/schemas/Unit'
        pricePerUnit:
          type: number
          format: float
        store:
          $ref: '#/components/schemas/Store'
    CreateProductInput:
      allOf:
        - $ref: '#/components/schemas/ProductInputBase'
        - required:
            - name
            - price
            - netto
            - unit
            - pricePerUnit
          example:
            name: Indomie Goreng
            description: The best instant fried noodle in Indonesia.
            images:
              - fileName: 'path-to-image.png'
                path: 'https://photo.com/path-to-image.png'
            categories:
              - food
            price: 3000
            netto: 80.00
            unit: g
            pricePerUnit: 37.50
            store:
              name: Indomaret Nglegok
              address: Jl. Raya Penataran, Nglegok 1, Nglegok, Kec. Nglegok, Kabupaten Blitar, Jawa Timur
    EditProductInput:
      allOf:
        - $ref: '#/components/schemas/ProductInputBase'
        - example:
            name: Indomie Goreng
            description: The best instant fried noodle in Indonesia.
            images:
              - fileName: 'path-to-image.png'
                path: 'https://photo.com/path-to-image.png'
            categories:
              - food
            price: 3000
            netto: 80.00
            unit: g
            pricePerUnit: 37.50
            store:
              name: Indomaret Nglegok
              address: Jl. Raya Penataran, Nglegok 1, Nglegok, Kec. Nglegok, Kabupaten Blitar, Jawa Timur
    ProductListWithPageResponse:
      allOf:
        - $ref: '#/components/schemas/PaginatedResponse'
        - type: object
          properties:
            docs:
              type: array
              items:
                $ref: '#/components/schemas/Product'

    ### ======================== User ======================== ###

    User:
      type: object
      properties:
        _id:
          type: string
          readOnly: true
        email:
          type: string
          format: email
        username:
          type: string
        hash:
          type: string
          writeOnly: true
        salt:
          type: string
          writeOnly: true
        categories:
          $ref: '#/components/schemas/Categories'
        units:
          $ref: '#/components/schemas/Units'
        stores:
          $ref: '#/components/schemas/Stores'
      example:
        _id: 507f1f77bcf86cd799439011
        email: johndoe@mail.com
        username: JohnDoe
        hash: hash_result
        salt: salt_result
        categories:
          - food
          - beverage
          - vegetable
          - dairy
          - meat
          - fruit
        units:
        stores:
          - type: object
            properties:
              name:
                type: string
              address:
                type: string
            example:
              name: Indomaret Nglegok
              address: Jl. Raya Penataran, Nglegok 1, Nglegok, Kec. Nglegok, Kabupaten Blitar, Jawa Timur
    UserRegisterInput:
      type: object
      properties:
        email:
          type: string
          format: email
        username:
          type: string
        password:
          type: string
        passwordRepeat:
          type: string
      example:
        email: johndoe@mail.com
        username: JohnDoe
        password: account_password
        passwordRepeat: account_password
    UserLoginInput:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      example:
        username: JohnDoe
        password: account_password`

    ### ======================== General ======================== ###

    Image:
      type: object
      properties:
        publicId:
          type: string
        url:
          type: string
      example:
        publicId: public_id
        url: https://photo.com/path-to-image.png
    Categories:
      type: array
      description: An array of product category tags.
      uniqueItems: true
      items:
        type: string
        description: A default product categories.
      example:
        - food
        - beverage
        - vegetable
        - dairy
        - meat
        - fruit
    Units:
      type: array
      description: An array of product measuring units.
      minItems: 1
      uniqueItems: true
      items:
        $ref: '#/components/schemas/Unit'
      example:
        - g
        - kg
        - ml
        - l
        - pcs
    Unit:
      type: string
      description: The default list of measuring units.
      enum:
        - g
        - kg
        - ml
        - l
        - pcs
    Store:
      type: object
      properties:
        name:
          type: string
        address:
          type: string
      example:
        name: Indomaret Nglegok
        address: Jl. Raya Penataran, Nglegok 1, Nglegok, Kec. Nglegok, Kabupaten Blitar, Jawa Timur
    Stores:
      type: array
      items:
        $ref: '#/components/schemas/Store'
    Page:
      type: integer
      minimum: 1
      default: 1
      example: 1
    Limit:
      type: integer
      enum:
        - 10
        - 25
        - 50
      default: 10
      example: 10
    PaginatedResponse:
      type: object
      properties:
        docs:
          type: array
        page:
          $ref: '#/components/schemas/Page'
        limit:
          $ref: '#/components/schemas/Limit'
        totalDocs:
          type: integer
          example: 120
    ResponseStatus:
      type: string
      enum:
        - ok
        - error
      default: ok

  parameters:
    pageParam:
      name: page
      in: query
      description: The current page for the requested data list.
      schema:
        $ref: '#/components/schemas/Page'
      required: true
    limitParam:
      name: limit
      in: query
      description: The amount of data per page.
      schema:
        $ref: '#/components/schemas/Limit'
    sortParam:
      name: sort
      in: query
      description: Sort key of an item list.
      schema:
        type: string
        enum:
          - createdAt
          - -createdAt
        default: -createdAt
    idParam:
      name: id
      in: path
      description: ID parameter for a specific data.
      schema:
        type: string
        example: 507f1f77bcf86cd799439011
      required: true
